### ISSUE TITLE
Set OTB environment variables

### ISSUE THREAD

**Issue by dutri001** [OSGeo/OSGeoLive#58]
The OTB python API currently does not work "out of the box".

`PYTHONPATH=/usr/lib/otb/python` and `ITK_AUTOLOAD_PATH=/usr/lib/otb/applications` have to be set by the user.
Could that be done directly when building the image?

**Comment by kalxas** [comment]
Please open a new ticket here:
https://trac.osgeo.org/osgeo/report/10

We are not currently using GitHub as an issue tracker.
